max_width = 80
comment_width = 80
match_block_trailing_comma = true
wrap_comments = true
edition = "2018"
indent_style = "Block"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
format_strings = true
merge_imports = true
force_multiline_blocks = true
space_after_colon = true
struct_field_align_threshold = 10
spaces_around_ranges = false
trailing_comma = "Vertical"
tab_spaces = 4
match_arm_blocks = true
blank_lines_upper_bound = 1
